# Generated by Django 3.0.3 on 2020-02-18 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockEx', '0002_gamesettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameSettings',
            new_name='GameSetting',
        ),
    ]
