# Generated by Django 3.0.3 on 2020-02-20 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockEx', '0003_auto_20200218_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesetting',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 2, 52, 6, 662387)),
            preserve_default=False,
        ),
    ]
