# Generated by Django 3.0.3 on 2020-02-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockEx', '0004_gamesetting_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesetting',
            name='span',
        ),
    ]
