# Generated by Django 3.0.3 on 2020-02-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockEx', '0007_stockpurchase_stockpurchaseone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockpurchaseone',
            name='stock_purchase',
        ),
        migrations.DeleteModel(
            name='StockPurchase',
        ),
        migrations.DeleteModel(
            name='StockPurchaseOne',
        ),
    ]
