# Generated by Django 3.0.3 on 2020-02-23 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockEx', '0009_onestockrecord_transactionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStockHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('holdings', models.IntegerField()),
                ('average_cost', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
