# Generated by Django 3.0.3 on 2020-02-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockEx', '0010_userstockholding'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='company',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OneStockRecord',
        ),
    ]
