# Generated by Django 3.0.3 on 2020-02-26 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockEx', '0011_auto_20200224_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesetting',
            name='reload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 13, 9, 0, 708535)),
            preserve_default=False,
        ),
    ]
