# Generated by Django 3.0.3 on 2020-02-27 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockEx', '0012_gamesetting_reload_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='histstockdata',
            old_name='belong',
            new_name='stock',
        ),
    ]
