# Generated by Django 3.0.3 on 2020-02-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockEx', '0014_auto_20200228_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstockholding',
            name='stock_symbol',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
