# Generated by Django 3.0.3 on 2020-03-01 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockEx', '0016_auto_20200229_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='img_roload_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 1, 12, 3, 17, 26352)),
            preserve_default=False,
        ),
    ]
